version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        environment:
            # Dokploy UI'dan environment variables'ları çek
            - APP_NAME=${APP_NAME:-Laravel}
            - APP_ENV=${APP_ENV:-production}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG:-false}
            - APP_URL=${APP_URL:-http://localhost:8080}

            # Octane settings
            - OCTANE_SERVER=${OCTANE_SERVER:-frankenphp}
            - OCTANE_HOST=${OCTANE_HOST:-0.0.0.0}
            - OCTANE_PORT=${OCTANE_PORT:-80}
            - OCTANE_WORKERS=${OCTANE_WORKERS:-4}
            - OCTANE_MAX_REQUESTS=${OCTANE_MAX_REQUESTS:-1000}

            # Database
            - DB_CONNECTION=${DB_CONNECTION:-mysql}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT:-3306}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

            # Redis
            - REDIS_CLIENT=${REDIS_CLIENT:-phpredis}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - REDIS_PASSWORD=${REDIS_PASSWORD}

            # Cache & Sessions
            - CACHE_STORE=${CACHE_STORE:-redis}
            - SESSION_DRIVER=${SESSION_DRIVER:-redis}
            - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}
            - BROADCAST_CONNECTION=${BROADCAST_CONNECTION:-redis}

            # Horizon
            - HORIZON_BALANCE=${HORIZON_BALANCE:-auto}
            - HORIZON_MAX_PROCESSES=${HORIZON_MAX_PROCESSES:-5}
            - HORIZON_MEMORY=${HORIZON_MEMORY:-256}

            # Performance
            - OPCACHE_ENABLE=${OPCACHE_ENABLE:-true}
            - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-100M}
            - POST_MAX_SIZE=${POST_MAX_SIZE:-100M}
            - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME:-300}

            # Logging
            - LOG_CHANNEL=${LOG_CHANNEL:-stack}
            - LOG_LEVEL=${LOG_LEVEL:-info}

        networks:
            - dokploy-network
        labels:
            - traefik.enable=true
            - traefik.docker.network=dokploy-network
            - traefik.http.routers.laravel-app.rule=Host(`hehetest.onaonbir.services`)
            - traefik.http.routers.laravel-app.entrypoints=web
            - traefik.http.services.laravel-app.loadbalancer.server.port=80
            - traefik.http.routers.laravel-app.service=laravel-app
        restart: unless-stopped
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3

networks:
    dokploy-network:
        external: true
