version: '3.8'

services:
    laravel:
        build: .
        ports:
            - "8080:8080"
        environment:
            # Dokploy environment variables'larını buraya referans et
            - APP_NAME=${APP_NAME:-Laravel}
            - APP_ENV=${APP_ENV:-production}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG:-false}
            - APP_URL=${APP_URL:-http://localhost:8080}
            - DB_CONNECTION=${DB_CONNECTION:-mysql}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT:-3306}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_CLIENT=${REDIS_CLIENT:-phpredis}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - CACHE_STORE=${CACHE_STORE:-redis}
            - SESSION_DRIVER=${SESSION_DRIVER:-redis}
            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}
            - HORIZON_BALANCE=${HORIZON_BALANCE:-auto}
            - HORIZON_MAX_PROCESSES=${HORIZON_MAX_PROCESSES:-5}
        networks:
            - dokploy-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

networks:
    dokploy-network:
        external: true
