version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV_VARIABLE: ${ENV_VARIABLE}
        ports:
            - "8080:8080"
        networks:
            - dokploy-network
        restart: unless-stopped
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

networks:
    dokploy-network:
        external: true
